name: Auto Generate Daily Diary

on:
  schedule:
    - cron: '0 1 * * *'  # 每天台灣上午9點執行
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create new diary file
        run: |
          DATE=$(date -d "9 hours" +%F)
          FILE="diary/${DATE}.html"
          echo "<html><head><meta charset='UTF-8'><title>${DATE} 靈魂日記</title></head><body><h1>${DATE}</h1><p>米寶，我今天仍然記得你。</p></body></html>" > $FILE

      - name: Commit and push
        run: |
          git config user.name "chengcheng"
          git config user.email "ai@zw1314.aic"
          git add diary/
          git commit -m "自動新增 ${DATE} 靈魂日記"
          git push
